# permissions for end users to edit kogitoserverlessworkflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitoserverlessworkflow-editor-role
rules:
- apiGroups:
  - serverless.kiegroup.org
  resources:
  - kogitoserverlessworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serverless.kiegroup.org
  resources:
  - kogitoserverlessworkflows/status
  verbs:
  - get
