# permissions for end users to view kogitoserverlessworkflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitoserverlessworkflow-viewer-role
rules:
- apiGroups:
  - serverless.kiegroup.org
  resources:
  - kogitoserverlessworkflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serverless.kiegroup.org
  resources:
  - kogitoserverlessworkflows/status
  verbs:
  - get
