---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kie.kogito.sw.org
  resources:
  - kogitoserverlessworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kie.kogito.sw.org
  resources:
  - kogitoserverlessworkflows/finalizers
  verbs:
  - update
- apiGroups:
  - kie.kogito.sw.org
  resources:
  - kogitoserverlessworkflows/status
  verbs:
  - get
  - patch
  - update
